build_targets:
- commands:
  - chmod +x yourbased.sh
  - sh ./yourbased.sh
  container:
    image: yourbase/yb_ubuntu:16.04
  name: default
  environment:
    - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
    - RUBY_GC_HEAP_INIT_SLOTS=600000
    - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
    - DISABLE_DATABASE_ENVIRONMENT_CHECK=true
    - DATABASE_ADAPTER=postgresql
    - DATABASE_USERNAME=postgres
    - PGHOST={{ .Containers.IP "db" }}
  dependencies:
      containers:
        db:
          image: postgres:10.10
          environment:
            - POSTGRES_PASSWORD=
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
          port_check:
            port: 5432
            timeout: 45
ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - ruby:2.5.3
